version: '3.9'
services:
  api:
    build: .
    container_name: api
    command: npm run dev
    depends_on:
      - postgres_dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development

  postgres_dev:
    image: postgres:latest
    container_name: postgres_dev
    ports:
      - 6000:5432
    env_file:
      - .env.development
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    ports:
      - 6001:5432
    env_file:
      - .env.test

volumes:
  postgres-data:
