FROM node:18

WORKDIR /app

COPY ["package*.json", ".env.production", "./"]

RUN npm install

COPY prisma/schema.prisma ./prisma/

RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

RUN npm start